### ISSUE TITLE
STOP_ON_FAILURE not working for POJO rules

### ISSUE THREAD

**Issue by duttkin** [deliveredtechnologies/rulebook#159]
I am using version 0.11 and the STOP_ON_FAILURE  is not working for POJO rules.  I created a simple rule to validate, see below.  When the exception is thrown, not only does the next rule in the chain execute but the auditor marks it as executed.

@Rule(order = 2, ruleChainAction = RuleChainActionType.STOP_ON_FAILURE)
public class Rule2 {

	@Given("myInput")
	private String input;

	@Result
	private String result;

	@When
	public boolean when() {
		if (true) {
			throw new NullPointerException();
		}
		return true;
	}

	@Then
	public RuleState then() {
		result = "success";
		return RuleState.BREAK;
	}

}

**Comment by Clayton7510** [comment]
Thanks for raising this. I'll check it out this weekend. My apologies for the delayed response - life events. :/

**Comment by mikelear** [comment]
Hi did you get chance to look at this , I've been trying to setup some examples to show the Rule flow and when I create some simple examples (similar to above) it looks like (with POJO rules) that the RuleChainActionType isn't working as expected. 
I can provide some examples if needed

**Comment by mikelear** [comment]
hi @Clayton7510 just checking if you had chance to look into this , if not I'll have a look over the weekend
