### ISSUE TITLE
Update reflections dependency to 0.9.12

### ISSUE THREAD

**Issue by azell** [deliveredtechnologies/rulebook#178]
We have seen multithreaded exceptions with reflections 0.9.10 likely due to https://github.com/ronmamo/reflections/issues/81 .  The bug appears to be fixed in 0.9.12.

**Comment by Clayton7510** [comment]
Thanks! I'll get it updated.

**Comment by Clayton7510** [comment]
I tried updating to 0.9.12, however there are breaking changes in 0.9.12. So, I guess it's staying on 0.9.10 until the next release.

**Comment by azell** [comment]
Perhaps a quicker fix would be to synchronize calls to reflections until an upgrade to 0.9.12.
